[package]
name = "facade_attr"
version = "0.1.0"
authors = ["Christopher Bacher <mindsbackyard@gmail.com>"]

[dependencies]
synom = "0.11"
quote = "0.3"

[dependencies.syn]
version = "0.11"
features = ["full", "parsing"]

[lib]
proc-macro = true
